In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a



array([1, 2, 3, 4])

In [3]:
a[0]


1

In [4]:
a[1]

2

In [5]:
a.size


4

In [6]:
a.len()


AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [7]:
help(a)


Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any object that can

In [8]:
import sys

In [9]:
sys.getsizeof(5) * len(

SyntaxError: incomplete input (2344916994.py, line 1)

In [10]:
b = 100

In [11]:
sys.getsizeof(5) * len(b)


TypeError: object of type 'int' has no len()

In [12]:
b = range(100)
sys.getsizeof(5) * len(b)


2800

In [13]:
a.size*a.itemsize



16

In [14]:
a.size * a.itemsize

16

In [15]:
a = arange(100)

NameError: name 'arange' is not defined

In [16]:
a= np.arange(100)
a.itemsize * a.size


400

In [17]:
a.itemsize?

Type:        int
String form: 4
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating-point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

In [18]:
import time

In [19]:
time.time()


1773605443.323366

In [20]:
start = time.time()
a=np.arange(1000000000)

b=np.arange(1000000000)

a+b
end = time.time()

time2 =end - start


MemoryError: Unable to allocate 3.73 GiB for an array with shape (1000000000,) and data type int32

In [21]:
time2


NameError: name 'time2' is not defined

In [22]:
start = time.time()
a=range(1000000)

b=range(1000000)

z= [for x,y in zip(a,b)]
end = time.time()

time2 =end - start


SyntaxError: invalid syntax (439074377.py, line 6)

In [23]:
start = time.time()
l1=range(100000)
l2=range(100000)
res = [(x,y) for x,y in zip(l1,l2)]
end = time.time()
end - start


0.04108834266662598

In [24]:
a=np.arange(100000)
b=np.arange(100000)
start = time.time()

a+b
end = time.time()
end - start


0.010046958923339844

In [25]:
import numpy as np
sis = np.array([[1,2,3],[9,3,6],[44,34,88],[18,34,22],[34,45,100]])
sis

array([[  1,   2,   3],
       [  9,   3,   6],
       [ 44,  34,  88],
       [ 18,  34,  22],
       [ 34,  45, 100]])

In [26]:
sis.ndim

2

In [27]:
sis.size



15

In [28]:
sis.itemsize


4

In [29]:
sis = np.array([[1,2,3],[22,33,44]],dtype=np.float64)

In [30]:
sis.itemsize

8

In [31]:
sis = sis.astype(complex)

In [32]:
sis.itemsize

16

In [33]:
sis

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [22.+0.j, 33.+0.j, 44.+0.j]])

In [34]:
sis = sis.astype(int)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_31648\1646259465.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  sis = sis.astype(int)


In [35]:
z = np.array([[1,2,3],[4,5,6]])
z.sum()

21

In [36]:
z.sum(axis=0)

array([5, 7, 9])

In [37]:
z.sum(axis=1)

array([ 6, 15])

In [38]:
z.max()

6

In [39]:
z.min()

1

In [40]:
z.shape()

TypeError: 'tuple' object is not callable

In [41]:
z.shape

(2, 3)

In [42]:
z.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
z.ravel()

array([1, 2, 3, 4, 5, 6])

In [130]:
np.sqrt(x)

11.0

In [ ]:
np.linspace(1,6,7)

In [131]:
np.std(x)

0.0

In [132]:
np.mean(x)

121.0

In [133]:
np.median(x)

121.0

In [ ]:
np.arange(10)

In [48]:
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [ ]:
np.zeros((3,4))

In [49]:
np.ones((8,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
a = np.array([[1,2],[3,4],[5,6]])

In [51]:
b= np.array([[20,33],[30,50],[20,30]])

In [52]:
a+b

array([[21, 35],
       [33, 54],
       [25, 36]])

In [53]:
a-b

array([[-19, -31],
       [-27, -46],
       [-15, -24]])

In [54]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [55]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
a = np.array([[1,2],[3,4]])

In [56]:
b= np.array([[1,2],[3,4]])

In [57]:
a.dot(b)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [58]:
a=np.arange(16).reshape(4,4)


In [59]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
a[0,3]

3

In [61]:
a[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
a[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [63]:
a[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [64]:
for x in a:
    print(x)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [65]:
for x in a.flat:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [66]:
a=np.arange(6).reshape(3,2)

b = np.arange(6,12).reshape(3,2)

In [67]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [68]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [69]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [70]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [71]:
a=np.arange(30).reshape(2,15)

In [72]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [73]:
res = np.hsplit(a,3)

In [74]:
res

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [75]:
res[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [76]:
res[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [77]:
help(res)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __it

In [78]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [79]:
a=np.arange(12).reshape(3,4)

In [80]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
b=a>4

In [82]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [83]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [84]:
a[b]=0

In [85]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [88]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [89]:
for x in np.nditer(a,order="F",flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [90]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [91]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [92]:
b=np.arange(3,10,3).reshape(3,1)

In [93]:
b

array([[3],
       [6],
       [9]])

In [94]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 6
25 6
36 6
49 6
64 9
81 9
100 9
121 9


In [95]:
import pandas as pd
df = pd.read_csv("nyc_weather.csv")

In [96]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109


In [97]:
df['Temperature'].max()

50

In [98]:
df['EST'][df['Events']=="Rain"]

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [99]:
df.fillna(0,inplace=True)

In [100]:
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,0,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,0,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,0,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,0,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,0,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,0,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,0.0,1.8,7,Rain,109


In [101]:
df['WindSpeedMPH'].mean()

6.225806451612903

In [102]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,0,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,0,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,0,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333


In [103]:
df.shape

(31, 11)

In [104]:
rows , cols = df.shape

In [105]:
rows

31

In [106]:
cols

11

In [107]:
df.tail()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,0,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,0,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,0,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,0,241


In [108]:
df[4:9]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,0,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,0,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,0,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76


In [109]:
df['Temperature']

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [110]:
df.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [111]:
df[['Temperature','Humidity','Events']]

,Temperature,Humidity,Events
0,38,52,0
1,36,46,0
2,40,47,0
3,25,44,0
4,20,41,0
5,33,35,0
6,39,33,0
7,39,64,0
8,44,77,Rain
9,50,71,Rain


In [112]:
df['Temperature'][df.Temperature == df.Temperature.max()]

9    50
Name: Temperature, dtype: int64

In [113]:
df[['Temperature','Humidity']][df['Humidity']==df['Humidity'].max()]

,Temperature,Humidity
22,26,78


In [114]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.225806,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,3.422569,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,0.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.000000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000


In [115]:
df.VisibilityMiles.max()

10

In [116]:
df.set_index('Temperature')

,EST,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Temperature,,,,,,,,,,
38,1/1/2016,23,52,30.03,10,8.0,0,5,0,281
36,1/2/2016,18,46,30.02,10,7.0,0,3,0,275
40,1/3/2016,21,47,29.86,10,8.0,0,1,0,277
25,1/4/2016,9,44,30.05,10,9.0,0,3,0,345
20,1/5/2016,-3,41,30.57,10,5.0,0,0,0,333
33,1/6/2016,4,35,30.50,10,4.0,0,0,0,259
39,1/7/2016,11,33,30.28,10,2.0,0,3,0,293
39,1/8/2016,29,64,30.20,10,4.0,0,8,0,79
44,1/9/2016,38,77,30.16,9,8.0,T,8,Rain,76


In [117]:
df.set_index('Temperature',inplace=True)

In [118]:
df.head()

,EST,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Temperature,,,,,,,,,,
38,1/1/2016,23,52,30.03,10,8.0,0,5,0,281
36,1/2/2016,18,46,30.02,10,7.0,0,3,0,275
40,1/3/2016,21,47,29.86,10,8.0,0,1,0,277
25,1/4/2016,9,44,30.05,10,9.0,0,3,0,345
20,1/5/2016,-3,41,30.57,10,5.0,0,0,0,333


In [119]:
df.reset_index(inplace=True)

In [120]:
df.head(1)

,Temperature,EST,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,38,1/1/2016,23,52,30.03,10,8.0,0,5,0,281


In [121]:
df.loc[38]

KeyError: 38

In [122]:
df.set_index('Sea Level PressureIn',inplace=True)

In [123]:
df.tail(10)

,Temperature,EST,DewPoint,Humidity,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Sea Level PressureIn,,,,,,,,,,
30.21,26,1/22/2016,6,41,9,0.0,0.01,3,Snow,34
29.77,26,1/23/2016,21,78,1,16.0,2.31,8,Fog-Snow,42
29.92,28,1/24/2016,11,53,8,6.0,T,3,Snow,327
30.25,34,1/25/2016,18,54,10,3.0,0,2,0,286
30.03,43,1/26/2016,29,56,10,7.0,0,2,0,244
30.03,41,1/27/2016,22,45,10,7.0,T,3,Rain,311
29.90,37,1/28/2016,20,51,10,5.0,0,1,0,234
29.58,36,1/29/2016,21,50,10,8.0,0,4,0,298
30.01,34,1/30/2016,16,46,10,7.0,0,0,0,257


In [124]:
df.loc[30.21]

Temperature               26
EST                1/22/2016
DewPoint                   6
Humidity                  41
VisibilityMiles            9
WindSpeedMPH             0.0
PrecipitationIn         0.01
CloudCover                 3
Events                  Snow
WindDirDegrees            34
Name: 30.21, dtype: object

In [125]:

weather_data = {
'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
'temperature': [32, 35, 28],
'windspeed': [6,7,2],
'event': ['Rain', 'Sunny', 'Snow']
}


df = pd.DataFrame(weather_data)

df


,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,35,7,Sunny
2,1/3/2017,28,2,Snow


In [126]:

# way 4 (python tuple list)
weather_data = [
('1/1/2017', 32, 6, 'Rain'),
('1/2/2017', 35, 7, 'Sunny'),
('1/3/2017', 28, 2, 'Snow')
]

df = pd.DataFrame(weather_data,columns=["day",'temp',"speed","event"])



In [127]:
df

,day,temp,speed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,35,7,Sunny
2,1/3/2017,28,2,Snow


In [128]:
# way 5 (python dictionary list)
weather_data = [
{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
{'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
{'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'}
]

df = pd.DataFrame(weather_data)

In [129]:
df

,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,35,7,Sunny
2,1/3/2017,28,2,Snow
